const tintColorLight = '#2196F3';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    primary: '#2196F3',
    secondary: '#4CAF50',
    accent: '#FF7F00',
    danger: '#F44336',
    warning: '#FFA000',
    info: '#00BCD4',
    success: '#4CAF50',
    lightBlue: '#E3F2FD',
    lightGreen: '#E8F5E9',
    lightPurple: '#EDE7F6',
    lightYellow: '#FFF8E1',
    lightCyan: '#E0F7FA',
    gradientStart: '#E57373',
    gradientEnd: '#9C27B0',
  },
  dark: {
    text: '#fff',
    background: '#121212',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    primary: '#90CAF9',
    secondary: '#A5D6A7',
    accent: '#FFAB40',
    danger: '#EF9A9A',
    warning: '#FFD54F',
    info: '#80DEEA',
    success: '#A5D6A7',
    lightBlue: '#1A2737',
    lightGreen: '#1A2E1A',
    lightPurple: '#2A1A2A',
    lightYellow: '#2E2A1A',
    lightCyan: '#1A2E2E',
    gradientStart: '#5D4037',
    gradientEnd: '#4A148C',
  },
};
